# Generated by Django 5.2.7 on 2025-10-09 14:00

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('about', models.TextField()),
                ('designation', models.CharField(choices=[('islamic_scholar', 'Islamic Scholar'), ('imam', 'Imam'), ('qari', 'Qari'), ('mufti', 'Mufti'), ('teacher', 'Islamic Teacher'), ('principal', 'Madrasa Principal')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='company_api.company')),
            ],
        ),
    ]
