# Generated by Django 5.2.7 on 2025-10-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('organisation', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('company', 'Company'), ('university', 'University')], max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('it', 'IT'), ('non_it', 'Non IT'), ('islamic', 'Islamic')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('ceo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
